version: 2.1

jobs:
  build:
    docker:
      - image: node:22-alpine
    steps:
      - checkout
      - run: npm install
      - run: npm run build

  deploy:
    docker:
      - image: node:22-alpine
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install sshpass
          command: apk add --no-cache sshpass
      - run: |
          # Build the Docker image
          docker build -t nextjs-app .
          
          # Tag the image for Docker Hub
          docker tag nextjs-app pushkarcdn/nextjs-app:latest
          
          # Log in to Docker Hub using CircleCI environment variables
          echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          
          # Push the image to Docker Hub
          docker push pushkarcdn/nextjs-app:latest
      - run:
          name: SSH into Azure VM and Deploy
          command: |
            sshpass -p "$AZURE_SSH_PASSWORD" ssh -o StrictHostKeyChecking=no "$AZURE_SSH_USERNAME"@$AZURE_VM_IP "
            docker pull pushkarcdn/nextjs-app:latest &&
            docker stop nextjs-app || true &&
            docker rm nextjs-app || true &&
            docker run -d -p 3000:3000 --name nextjs-app pushkarcdn/nextjs-app:latest
            "

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
