version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:22-alpine
    steps:
      - checkout
      - run: npm install
      - run: npm run build

  deploy:
    docker:
      - image: circleci/node:22-alpine
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build -t nextjs-app .
          docker tag nextjs-app pushkarcdn/nextjs-app:latest
          echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker push pushkarcdn/nextjs-app:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
