version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:21.7.1
    steps:
      - checkout
      - run: npm install
      - run: npm run build

  deploy:
    docker:
      - image: docker:20.10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Dependencies
          command: apk add --no-cache bash openssh-client sshpass
      - run:
          name: Build and Push Docker Image
          command: |
            docker buildx create --use
            docker buildx build --platform linux/arm64 -t nextjs-app .
      - run:
          name: Docker Login
          command: |
            docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            docker push pushkarcdn/nextjs-app:latest
      - run:
          name: SSH into Azure VM and Deploy
          command: |
            sshpass -p "$AZURE_SSH_PASSWORD" ssh -tt -o StrictHostKeyChecking=no "$AZURE_SSH_USERNAME"@$AZURE_VM_IP \<< EOF
              docker system prune -f
              docker pull pushkarcdn/nextjs-app:latest
              docker stop nextjs-app || true
              docker rm -f nextjs-app || true
              docker run -d -p 3000:3000 --restart unless-stopped --name nextjs-app pushkarcdn/nextjs-app:latest
            EOF

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
